export const wiipoAssets = {
  capa: {
    comeceAqui: "/wiipo/capa/comece-aqui.jpg",
    workInPublic: "/wiipo/capa/work-in-public.jpg",
    hero: "/wiipo/capa/hero.jpg",
    conquistas: "/wiipo/capa/conquistas.jpg",
    vagas: "/wiipo/capa/vagas.jpg",
    linkedin: "/wiipo/capa/linkedin.jpg",
  },
  perfil: {
    avatar: "/wiipo/perfil/avatar.jpg",
    avatarCream: "/wiipo/perfil/avatar-cream.jpg",
  },
  ui: {
    idle: "/wiipo/ui/idle.jpg",
    peek: "/wiipo/ui/peek.jpg",
    wave: "/wiipo/ui/wave.jpg",
    point: "/wiipo/ui/point.jpg",
    celebrate: "/wiipo/ui/celebrate.jpg",
  },
  modelo: {
    ficha: "/wiipo/modelo/ficha.jpg",
    turnaround: "/wiipo/modelo/turnaround.jpg",
  },
  classroom: {
    empty: "/wiipo/classroom/empty.png",
    emptySolo: "/wiipo/classroom/empty-solo.png",
  },
  logo: {
    mark: "/wiipo/logo/mark.png",
    wordmark: "/wiipo/logo/wordmark.png",
    lockup: "/wiipo/logo/lockup.png",
    lockupFlat: "/wiipo/logo/lockup-flat.png",
    rosto3d: "/wiipo/logo/rosto-3d.png",
  },
  stickers: {
    oficialIdle: "/wiipo/stickers/oficial-idle.png",
    oficialWave: "/wiipo/stickers/oficial-wave.png",
    oficialThink: "/wiipo/stickers/oficial-think.png",
    oficialPeek: "/wiipo/stickers/oficial-peek.png",
    oficialSit: "/wiipo/stickers/oficial-sit.png",
    oficialPoint: "/wiipo/stickers/oficial-point.png",
    bone: "/wiipo/stickers/bone.png",
    oculos: "/wiipo/stickers/oculos.png",
    gorro: "/wiipo/stickers/gorro.png",
    fone: "/wiipo/stickers/fone.png",
    coroa: "/wiipo/stickers/coroa.png",
    cachecol: "/wiipo/stickers/cachecol.png",
  },
  icones: {
    busto: "/wiipo/icones/busto.png",
    rosto: "/wiipo/icones/rosto.png",
    frente: "/wiipo/icones/frente.png",
    tresQuartos: "/wiipo/icones/tres-quartos.png",
    peek: "/wiipo/icones/peek.png",
    wave: "/wiipo/icones/wave.png",
  },
  empty: {
    comments: "/wiipo/empty/comments.png",
    posts: "/wiipo/empty/posts.png",
  },
  assinatura: {
    idle: "/wiipo/assinatura/idle.png",
    peek: "/wiipo/assinatura/peek.png",
    point: "/wiipo/assinatura/point.png",
    celebrate: "/wiipo/assinatura/celebrate.png",
    createWave: "/wiipo/assinatura/create-wave.png",
    createPresent: "/wiipo/assinatura/create-present.png",
  },
} as const;
